version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:14.15-browsers

jobs:
  TheTest:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run: npm run test

workflows:
  version: 2
  TheSetupAndTest:
    jobs:
      - TheTest
